"""Tokens semânticos da interface administrativa."""

from Back_end.interface.theme.colors import (
    BLACK,
    WHITE,
    NAVY,
    BLUE_DARK,
    CYAN_LIGHT,
    CYAN_DARK,
    GREEN_DARK,
    YELLOW_ORANGE,
    RED,
)


# Página
PAGE_BACKGROUND = "#F5F7FA"
PAGE_BACKGROUND_DARK = "#12162B"


# Superfícies
SURFACE = WHITE
SURFACE_DARK = "#191F38"

SURFACE_SECONDARY = "#EEF3F7"
SURFACE_SECONDARY_DARK = "#202844"


# Navegação
SIDEBAR_BACKGROUND = NAVY
SIDEBAR_BACKGROUND_ACTIVE = BLUE_DARK

SIDEBAR_TEXT = WHITE
SIDEBAR_TEXT_MUTED = "rgba(255, 255, 255, 0.68)"

SIDEBAR_ACCENT = CYAN_LIGHT


# Cabeçalho
HEADER_BACKGROUND = WHITE
HEADER_BACKGROUND_DARK = "#191F38"


# Texto
TEXT_PRIMARY = NAVY
TEXT_SECONDARY = "#61697A"
TEXT_MUTED = "#8B92A0"

TEXT_PRIMARY_DARK = WHITE
TEXT_SECONDARY_DARK = "#C7CDDA"


# Bordas
BORDER = "#DDE3EA"
BORDER_DARK = "#303A59"


# Ações
PRIMARY = NAVY
PRIMARY_HOVER = BLUE_DARK

ACCENT = CYAN_LIGHT
ACCENT_HOVER = CYAN_DARK


# Estados do sistema
SUCCESS = GREEN_DARK
WARNING = YELLOW_ORANGE
DANGER = RED

INFO = CYAN_DARK


# Básicos
TEXT_ON_DARK = WHITE
TEXT_ON_LIGHT = BLACK