"""add meta details and budget

Revision ID: 69b0adf60132
Revises: 7bc0f0432a5b
Create Date: 2026-09-17 10:48:10.577748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69b0adf60132'
down_revision: Union[str, Sequence[str], None] = '7bc0f0432a5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_orcamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meta_id', sa.Integer(), nullable=False),
    sa.Column('total_previsao', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_empenhado', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_liquidado', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_previsao_projeto', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_empenhado_projeto', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_liquidado_projeto', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_previsao_atividade', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_empenhado_atividade', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_liquidado_atividade', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_previsao_operacao_especial', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_empenhado_operacao_especial', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_liquidado_operacao_especial', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meta_id'], ['metas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_orcamentos_meta_id'), 'meta_orcamentos', ['meta_id'], unique=True)
    op.add_column('metas', sa.Column('status', sa.String(), nullable=True))
    op.add_column('metas', sa.Column('macro_tema_smae_id', sa.Integer(), nullable=True))
    op.add_column('metas', sa.Column('macro_tema_descricao', sa.String(), nullable=True))
    op.add_column('metas', sa.Column('sub_tema_smae_id', sa.Integer(), nullable=True))
    op.add_column('metas', sa.Column('sub_tema_descricao', sa.String(), nullable=True))
    op.add_column('metas', sa.Column('cronograma_smae_id', sa.Integer(), nullable=True))
    op.add_column('metas', sa.Column('atraso_grau', sa.String(), nullable=True))
    op.add_column('metas', sa.Column('raw_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_metas_ativo'), 'metas', ['ativo'], unique=False)
    op.create_index(op.f('ix_metas_atraso_grau'), 'metas', ['atraso_grau'], unique=False)
    op.create_index(op.f('ix_metas_macro_tema_smae_id'), 'metas', ['macro_tema_smae_id'], unique=False)
    op.create_index(op.f('ix_metas_status'), 'metas', ['status'], unique=False)
    op.create_index(op.f('ix_metas_sub_tema_smae_id'), 'metas', ['sub_tema_smae_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metas_sub_tema_smae_id'), table_name='metas')
    op.drop_index(op.f('ix_metas_status'), table_name='metas')
    op.drop_index(op.f('ix_metas_macro_tema_smae_id'), table_name='metas')
    op.drop_index(op.f('ix_metas_atraso_grau'), table_name='metas')
    op.drop_index(op.f('ix_metas_ativo'), table_name='metas')
    op.drop_column('metas', 'raw_detail')
    op.drop_column('metas', 'atraso_grau')
    op.drop_column('metas', 'cronograma_smae_id')
    op.drop_column('metas', 'sub_tema_descricao')
    op.drop_column('metas', 'sub_tema_smae_id')
    op.drop_column('metas', 'macro_tema_descricao')
    op.drop_column('metas', 'macro_tema_smae_id')
    op.drop_column('metas', 'status')
    op.drop_index(op.f('ix_meta_orcamentos_meta_id'), table_name='meta_orcamentos')
    op.drop_table('meta_orcamentos')
    # ### end Alembic commands ###
