"""add initiatives

Revision ID: 6df5232c55cc
Revises: ea62776455ab
Create Date: 2026-09-17 11:59:56.352262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6df5232c55cc'
down_revision: Union[str, Sequence[str], None] = 'ea62776455ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iniciativas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smae_id', sa.Integer(), nullable=False),
    sa.Column('meta_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['meta_id'], ['metas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iniciativas_codigo'), 'iniciativas', ['codigo'], unique=False)
    op.create_index(op.f('ix_iniciativas_meta_id'), 'iniciativas', ['meta_id'], unique=False)
    op.create_index(op.f('ix_iniciativas_smae_id'), 'iniciativas', ['smae_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_iniciativas_smae_id'), table_name='iniciativas')
    op.drop_index(op.f('ix_iniciativas_meta_id'), table_name='iniciativas')
    op.drop_index(op.f('ix_iniciativas_codigo'), table_name='iniciativas')
    op.drop_table('iniciativas')
    # ### end Alembic commands ###
