"""create metas table

Revision ID: 7bc0f0432a5b
Revises: 547355594417
Create Date: 2026-09-08 11:02:34.850593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7bc0f0432a5b'
down_revision: Union[str, Sequence[str], None] = '547355594417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smae_id', sa.Integer(), nullable=False),
    sa.Column('pdm_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('contexto', sa.Text(), nullable=True),
    sa.Column('complemento', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('tema_smae_id', sa.Integer(), nullable=True),
    sa.Column('tema_descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metas_codigo'), ['codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_metas_pdm_id'), ['pdm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metas_smae_id'), ['smae_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_metas_tema_smae_id'), ['tema_smae_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metas_tema_smae_id'))
        batch_op.drop_index(batch_op.f('ix_metas_smae_id'))
        batch_op.drop_index(batch_op.f('ix_metas_pdm_id'))
        batch_op.drop_index(batch_op.f('ix_metas_codigo'))

    op.drop_table('metas')
    # ### end Alembic commands ###
