"""add meta organizations and people

Revision ID: c4062538b24f
Revises: 4b994df0be05
Create Date: 2026-09-17 11:23:42.480984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4062538b24f'
down_revision: Union[str, Sequence[str], None] = '4b994df0be05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orgaos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smae_id', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.String(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orgaos_sigla'), 'orgaos', ['sigla'], unique=False)
    op.create_index(op.f('ix_orgaos_smae_id'), 'orgaos', ['smae_id'], unique=True)
    op.create_table('pessoas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smae_id', sa.Integer(), nullable=False),
    sa.Column('nome_exibicao', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pessoas_smae_id'), 'pessoas', ['smae_id'], unique=True)
    op.create_table('meta_orgaos',
    sa.Column('meta_id', sa.Integer(), nullable=False),
    sa.Column('orgao_id', sa.Integer(), nullable=False),
    sa.Column('responsavel', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['meta_id'], ['metas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['orgao_id'], ['orgaos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meta_id', 'orgao_id')
    )
    op.create_table('meta_pessoas',
    sa.Column('meta_id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('orgao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meta_id'], ['metas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['orgao_id'], ['orgaos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meta_id', 'pessoa_id', 'tipo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meta_pessoas')
    op.drop_table('meta_orgaos')
    op.drop_index(op.f('ix_pessoas_smae_id'), table_name='pessoas')
    op.drop_table('pessoas')
    op.drop_index(op.f('ix_orgaos_smae_id'), table_name='orgaos')
    op.drop_index(op.f('ix_orgaos_sigla'), table_name='orgaos')
    op.drop_table('orgaos')
    # ### end Alembic commands ###
