"""add meta teams

Revision ID: ea62776455ab
Revises: c4062538b24f
Create Date: 2026-09-17 11:31:28.891953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea62776455ab'
down_revision: Union[str, Sequence[str], None] = 'c4062538b24f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_equipes',
    sa.Column('meta_id', sa.Integer(), nullable=False),
    sa.Column('equipe_smae_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['meta_id'], ['metas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meta_id', 'equipe_smae_id', 'tipo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meta_equipes')
    # ### end Alembic commands ###
