// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/metas/:codigo": {
    params: {
      "codigo": string;
    };
  };
  "/logout": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/metas/:codigo" | "/logout" | "/admin" | "/login" | "/*";
  };
  "routes/[metas].$[codigo]._index.jsx": {
    id: "routes/[metas].$[codigo]._index";
    page: "/metas/:codigo";
  };
  "routes/[logout]._index.jsx": {
    id: "routes/[logout]._index";
    page: "/logout";
  };
  "routes/[admin]._index.jsx": {
    id: "routes/[admin]._index";
    page: "/admin";
  };
  "routes/[login]._index.jsx": {
    id: "routes/[login]._index";
    page: "/login";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/[404]._index.jsx": {
    id: "routes/[404]._index";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/[metas].$[codigo]._index": typeof import("./app/routes/[metas].$[codigo]._index.jsx");
  "routes/[logout]._index": typeof import("./app/routes/[logout]._index.jsx");
  "routes/[admin]._index": typeof import("./app/routes/[admin]._index.jsx");
  "routes/[login]._index": typeof import("./app/routes/[login]._index.jsx");
  "routes/_index": typeof import("./app/routes/_index.jsx");
  "routes/[404]._index": typeof import("./app/routes/[404]._index.jsx");
};